### ISSUE TITLE
For the dataset

### ISSUE THREAD

**Issue by YuxinFang21** [ushasi/Earth-on-Canvas-dataset#2]
Hello, your project and papper are both excellent. Can u send me your dataset? I  have send an e-mail to you.

**Comment by ushasi** [comment]
Emailed you the link.
Thanks,

**Comment by srdg** [comment]
Hello, could I also get a link to the dataset, please?

**Comment by ushasi** [comment]
Hi!
Please find the following link for downloading the dataset.
https://ieee-dataport.org/open-access/earth-canvas-6
Cheers!
